Fix signin flow in presence of Public and Private access
preview-code/rite-evaluation pull request #370
Opened 2016-09-25 10:50 UTC by txsmith

I split the sign-in functionality (previously all in `signIn()`) into two functions. One (`doSignIn`) performs the redirect-flow if and only if the user clicks one of the login buttons on the home page. The other (`checkSignedIn`) checks whether the redirect-flow was done and if the user is signed in properly.

If a user was not signed in (no GitHub token in local-store and no redirect-flow ongoing), then the user is redirected to the home page again.

Please check thoroughly!

2016-09-25 12:45 UTC, eanker commented
It all works as intended, and code wise I could not find something wrong, except one nit-picky comment.

Just one remark, when clicking on home we are automatically logged in, so we can not see the homepage anymore. Is this desired?

2016-09-25 12:45 UTC, eanker commented on src/ajax/firebase-authentication.html
> +          redirectDone = !!result.credential
This is the first occurrence of redirectDone, why is it not declared?
And the ; is missing.
Just change it to: `var redirectDone = !!result.credential;`

2016-09-25 13:14 UTC, txsmith commented
Please squash merge with the first commit message if OK

2016-09-25 13:16 UTC, eanker commented on src/projects/feature-bar.html
> +<!-- Copyright (c) 2016, preview-code
Was this an intended push?
I do not see this file used.

2016-09-25 13:20 UTC, txsmith commented on src/projects/feature-bar.html
> +<!-- Copyright (c) 2016, preview-code
Nope, oops

2016-09-25 13:22 UTC, eanker commented on src/preview-app.html
> +      if (this.page.page !== '') {
This doesn't work, we can not get off the homepage.
So, we we click login we are redirected to the homepage (etc.).

2016-09-25 13:22 UTC, eanker requested changes

2016-09-25 13:24 UTC, txsmith commented on src/preview-app.html
> +      if (this.page.page !== '') {
Done

2016-09-25 13:24 UTC, txsmith commented on src/ajax/firebase-authentication.html
> +          redirectDone = !!result.credential
Done

2016-09-25 13:28 UTC, eanker approved these changes

2016-09-25 13:29 UTC, eanker commented
Works as intended.

This pull request even fixes #366

2016-09-25 13:30 UTC, merged

2016-09-29 14:48 UTC, TimvdLippe commented on src/ajax/firebase-authentication.html
> +        waitingForSignIn: Boolean
Maybe you can also take advantage of [`statusKnown`](https://github.com/firebase/polymerfire/blob/master/firebase-auth.html#L115-L124)