Imports pull requests from github and add's them to firebase
preview-code/rite-evaluation pull request #387
Opened 2016-10-25 12:58 UTC by eanker

If a pull request is made via github no data is stored in firebase.
This means that certain features won't work, because the path in firebase does not exists. Therefore (pr specific) default data is stored in firebase, when there is no data stored.

Together with preview-code/backend#16

2016-11-30 13:22 UTC, txsmith requested changes
I still need to actually test this, but the code looks good. Just one comment on the default group name

2016-11-30 13:22 UTC, txsmith commented on src/projects/diff/hunk-sorter.html
> +          this.$.checkIfPathIsThere.body = defaultGroup;
Maybe we should alter the name of the default group to show the user that the changes were directly imported from GitHub

2016-11-30 13:46 UTC, eanker commented on src/projects/diff/hunk-sorter.html
> +          this.$.checkIfPathIsThere.body = defaultGroup;
I like this. Shall make the change.

2016-12-12 10:56 UTC, eanker commented
I reverted the rebase for now, as otherwise the backend doesn't work.
Will rebase when the other pr's are merged.

2016-12-12 11:55 UTC, eanker commented on src/projects/diff/hunk-sorter.html
> +          this.$.checkIfPathIsThere.body = defaultGroup;
Should we just change 'Unsorted Changes' to 'Imported from Github' or do we really want to do it only on import?

2017-02-13 10:04 UTC, txsmith commented on src/projects/diff/hunk-sorter.html
> +          this.$.checkIfPathIsThere.body = defaultGroup;
Unsorted changes always come from GitHub so I think we should just change the `Unsorted changes` string

2017-02-13 11:58 UTC, eanker commented
This pr should work now.

There was a problem with posting and then showing the first group comment, but I think I have fixed it.
It was sometimes hard to reproduce (no idea why it sometimes decided not to show), so look carefully at that.

2017-02-15 08:02 UTC, txsmith approved these changes

2017-02-15 08:03 UTC, txsmith commented
Confirmed working!

2017-02-15 08:03 UTC, merged