Changed epoch to date
preview-code/rite-evaluation pull request #431
Opened 2017-02-15 14:01 UTC by eanker

![image](https://cloud.githubusercontent.com/assets/5946438/22977601/9735b0b2-f38f-11e6-8ac8-34146ac25033.png)

2017-02-15 14:01 UTC, eanker commented
Is this ok, or shall I see if I can remove the 'GMT+0100 (CET)'

2017-02-20 13:36 UTC, txsmith requested changes

2017-02-20 13:36 UTC, txsmith commented on src/projects/pull-request/pull-request-comment.html
> +          value: 'shortA'
Should this not be `short`?

2017-02-20 13:42 UTC, eanker commented on src/projects/pull-request/pull-request-comment.html
> +          value: 'shortA'
Your totally right

2017-02-20 13:53 UTC, txsmith approved these changes

2017-02-20 13:53 UTC, merged