Added CI checks to the pull request view
preview-code/rite-evaluation pull request #442
Opened 2017-02-21 13:01 UTC by eanker

fixes #425 

Also made an element for the ci-button and therefore changed the list-item

![image](https://cloud.githubusercontent.com/assets/5946438/23165777/0d0fb352-f83e-11e6-9c9d-52f1fa385f0f.png)

![image](https://cloud.githubusercontent.com/assets/5946438/23165793/1e2c5b9a-f83e-11e6-85f1-2aa537f0f613.png)

![image](https://cloud.githubusercontent.com/assets/5946438/23165814/37f548ca-f83e-11e6-8c94-ceeee2f9107f.png)

2017-02-22 10:43 UTC, txsmith requested changes

2017-02-22 10:43 UTC, txsmith commented on src/util/ci-buttons.html
> +        <span class$="icondiv-failure [[status]]">
Can you change these outermost `<span>`s into `<div>`s? Otherwise the bounding-box of the elements becomes strange for larger icons. This can cause problems later on.

2017-02-22 10:43 UTC, txsmith commented on src/util/ci-buttons.html
> +        icon2: {
While you're editing this file; can you give these better names?

2017-02-22 10:43 UTC, txsmith commented on src/util/ci-buttons.html
> +          <iron-icon title="CI pending" class="icon-pending" icon="[[icon2]]"></iron-icon>
It would be nice to have a different icon for `pending` than the one for `failure`. GitHub uses a dot-like icon for this.

2017-02-22 11:56 UTC, TimvdLippe commented on src/util/ci-buttons.html
> +      is: 'ci-buttons',
This is just 1 button, so I would propose to name it `ci-indicator`

2017-02-22 11:56 UTC, TimvdLippe commented on test/util/ci-buttons.html
> +  <title>to-date-string-behavior tests</title>
Copy-pasta

2017-02-22 11:56 UTC, TimvdLippe commented on test/util/ci-buttons.html
> +  /*global ToDateStringBehavior*/
Copy-pasta

2017-02-23 08:16 UTC, txsmith approved these changes

2017-02-23 08:16 UTC, merged