Fixed the overflow of list items
preview-code/rite-evaluation pull request #450
Opened 2017-02-22 12:53 UTC by eanker

![image](https://cloud.githubusercontent.com/assets/5946438/23212249/1f8f9632-f906-11e6-9c14-e2168fa53982.png)

before:
![image](https://cloud.githubusercontent.com/assets/5946438/23212277/36c63e32-f906-11e6-987e-d59f93dd9e82.png)

Fixes #444

2017-02-22 12:54 UTC, eanker commented on src/list-items/list-item-label.html
> +        width: 120%;
Could you verify if this also works for you (it seemed to work in the devices overview)?
Otherwise I will change it back to 100%.

2017-02-22 13:11 UTC, eanker commented
This caused another error, so I will fix that first.

2017-02-22 13:13 UTC, eanker commented on src/list-items/list-item-label.html
> +        max-width: 120%;
Could you verify if this also works for you (it seemed to work in the devices overview)?
Otherwise I will change it back to 100%.

2017-02-23 08:14 UTC, txsmith requested changes

2017-02-23 08:14 UTC, txsmith commented on src/list-items/list-item-label.html
> +        max-width: 120%;
I'm afraid this is not a very good fix. The `list-item-label` is used in many other places and this change will restrict the size of the labels everywhere. Furthermore, 120% is an arbitrary number that could still not work on other screens than the ones we test. I'd think you can fix this in the place where `list-item-label` is used.

2017-02-23 08:43 UTC, eanker commented on src/list-items/list-item-label.html
> +        max-width: 120%;
Didn't got this fixed in the class it was used.

Is making a new type for this in list-item-label, also good for you?
I will then use max-width 100%, as this should always work. 

Maybe it was a bit shortsighted of me, as I saw no labels where broken by this change I thought it was ok.

2017-03-01 15:37 UTC, txsmith approved these changes

2017-03-01 15:37 UTC, merged